-- ============================================================
-- Migration: 009_tables_ai_ready
-- Description: AI-ready schema foundation — session recordings, reports, curriculum links
--
-- IMPORTANT: These tables are SCHEMA-ONLY for MVP.
--   - No Gemini pipeline implemented
--   - No recording processing implemented
--   - No RAG, embeddings, vector DB, OCR, or semantic comparison
--   - AI report status exposed in dashboards as placeholder states only
--
-- Future AI phase entry point:
--   Query: session_recordings WHERE processing_status = 'pending'
--          AND booking.recording_consent = true
--          AND booking.ai_analysis_consent = true
--   Then: retrieve recording → upload to Gemini → generate report → update ai_session_reports
--
-- Reversible: YES
-- ============================================================

-- ---------------------
-- session_recordings
-- Metadata for Merithub session recordings.
-- Recording retrieval requires both consents on the booking.
-- ---------------------
CREATE TABLE session_recordings (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id          UUID NOT NULL UNIQUE REFERENCES bookings(id),
  merithub_session_id UUID REFERENCES merithub_sessions(id) ON DELETE SET NULL,
  recording_url       TEXT,
  duration_seconds    INTEGER CHECK (duration_seconds > 0),
  processing_status   TEXT NOT NULL DEFAULT 'not_started' CHECK (
    processing_status IN ('not_started', 'pending', 'processing', 'completed', 'failed')
  ),
  consent_verified_at TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  session_recordings IS 'AI-ready: recording metadata. Gemini pipeline NOT implemented. Retrieved only when recording_consent AND ai_analysis_consent are both true on the booking.';
COMMENT ON COLUMN session_recordings.processing_status IS 'AI pipeline status. not_started until future AI phase is approved.';
COMMENT ON COLUMN session_recordings.consent_verified_at IS 'Set by server action when consent is confirmed before any retrieval.';

CREATE INDEX idx_recordings_booking_id ON session_recordings(booking_id);
CREATE INDEX idx_recordings_pending    ON session_recordings(processing_status)
  WHERE processing_status IN ('pending', 'processing');

-- ---------------------
-- ai_session_reports
-- Report lifecycle for AI-generated educational session reports (Arabic).
-- Status exposed in dashboards; actual content is null until AI phase.
-- ---------------------
CREATE TABLE ai_session_reports (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id     UUID NOT NULL UNIQUE REFERENCES bookings(id),
  recording_id   UUID REFERENCES session_recordings(id) ON DELETE SET NULL,
  status         report_status NOT NULL DEFAULT 'no_report',
  report_json    JSONB,
  report_text_ar TEXT,
  generated_at   TIMESTAMPTZ,
  error_message  TEXT,
  emailed_at     TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  ai_session_reports IS 'AI-ready: educational report lifecycle. Gemini generation NOT implemented. Dashboard shows status placeholder.';
COMMENT ON COLUMN ai_session_reports.report_text_ar IS 'Arabic narrative report. Generated by Gemini in future AI phase. Constructive educational language only — no medical/psychological labels.';
COMMENT ON COLUMN ai_session_reports.report_json IS 'Structured report data (JSON). Future AI phase populates this.';

CREATE INDEX idx_ai_reports_booking_id ON ai_session_reports(booking_id);
CREATE INDEX idx_ai_reports_status     ON ai_session_reports(status);

-- ---------------------
-- lesson_curriculum_links
-- Explicit join between a booking and a curriculum file.
-- Enables AI phase to retrieve curriculum context for the session.
-- ---------------------
CREATE TABLE lesson_curriculum_links (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id         UUID NOT NULL UNIQUE REFERENCES bookings(id),
  curriculum_file_id UUID NOT NULL REFERENCES curriculum_files(id),
  unit               TEXT,
  lesson_title       TEXT,
  linked_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE lesson_curriculum_links IS 'AI-ready: links bookings to curriculum files. Enables future AI analysis context retrieval. No AI processing in MVP.';

CREATE INDEX idx_curr_links_booking_id ON lesson_curriculum_links(booking_id);
CREATE INDEX idx_curr_links_file_id    ON lesson_curriculum_links(curriculum_file_id);

-- ============================================================
-- ROLLBACK:
-- DROP INDEX IF EXISTS idx_curr_links_file_id;
-- DROP INDEX IF EXISTS idx_curr_links_booking_id;
-- DROP TABLE IF EXISTS lesson_curriculum_links;
-- DROP INDEX IF EXISTS idx_ai_reports_status;
-- DROP INDEX IF EXISTS idx_ai_reports_booking_id;
-- DROP TABLE IF EXISTS ai_session_reports;
-- DROP INDEX IF EXISTS idx_recordings_pending;
-- DROP INDEX IF EXISTS idx_recordings_booking_id;
-- DROP TABLE IF EXISTS session_recordings;
-- ============================================================
